Update patch set 1
Patch Set 1:

Error: Package: python2-muranoclient-0.11.0-1.el7.noarch (validated)
           Requires: pyOpenSSL >= 0.14
           Installed: pyOpenSSL-0.13.1-3.el7.x86_64 (@base)
               pyOpenSSL = 0.13.1-3.el7

But we have update pyOpenSSL 0.15 in openstack-common: http://cbs.centos.org/koji/buildinfo?buildID=1500

Why is it available in buildroot?

Patch-set: 1