Avoid racy unit test
Found in one openstack-tempest FTBFS:
Failed 1 tests - output below:
tempest.tests.lib.cmd.test_check_uuid.TestCLInterface.test_fix_argument_yes
Traceback (most recent call last):
File "/builddir/build/BUILD/tempest-29.1.0/tempest/tests/lib/cmd/test_check_uuid.py", line 56, in test_fix_argument_yes
check_uuid.run()
File "/builddir/build/BUILD/tempest-29.1.0/tempest/lib/cmd/check_uuid.py", line 435, in run
pkg = importlib.import_module(args.package)
File "/usr/lib64/python3.6/importlib/init.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'check-uuidkkbq9p20'

mkopec said: "that's a racy unit test, it fails from time to time, we
fixed that several times (well, that's what we thought), we're checking
that right now .. anyway, it's a faulty test and this failure doesn't
meant there is something wrong with the code."

Change-Id: I82337d04d8564a7a30e314684fd72386e07e52d1
(cherry picked from commit dbf69bff097faf82ebf9e8bea4cda4944af743e2)